In [1]:
import numpy as np

# Using linspace: 10 numbers from 1 to 5
arr_linspace = np.linspace(1, 5, 10)
print("Array using linspace:\n", arr_linspace)

# Using eye: 4x4 identity matrix
arr_eye = np.eye(4)
print("\nArray using eye (4x4 identity matrix):\n", arr_eye)

# Using arange: numbers from 0 to 15 with step 3
arr_arange = np.arange(0, 16, 3)
print("\nArray using arange (0 to 15, step 3):\n", arr_arange)

Array using linspace:
 [1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]

Array using eye (4x4 identity matrix):
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Array using arange (0 to 15, step 3):
 [ 0  3  6  9 12 15]
